name: CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Add ssh key for vm
      run: ./.github/scripts/addssh.sh
      env:
        SSH_S: ${{ secrets.SSH_S }}

